site_name: s3gw Project Documentation
repo_url: https://github.com/aquarist-labs/s3gw
repo_name: aquarist-labs/s3gw
theme:
  name: material
  logo: https://raw.githubusercontent.com/aquarist-labs/s3gw/main/assets/images/s3gw-logo.png
  highlightjs: true
  features:
    - navigation.instant
markdown_extensions:
  - admonition

plugins:
  - search
  - external-markdown
nav:
  - Introduction: "index.md"
  - Contributing: "contributing.md"
  - Roadmap: "roadmap.md"
  - "Installation and Configuration":
      - Quickstart: "quickstart.md"
      - Installing k8s for s3gw: "s3gw-with-k8s.md"
      - Installing k3s for s3gw: "s3gw-with-k3s.md"
      - Installing s3gw with Helm charts: "helm-charts.md"
      - Configuring the s3gw: "config-s3gw.md"
  - Troubleshooting the s3gw: "troubleshoot-s3gw.md"
  - "Development Manual":
      - Developing the S3gw: "developing.md"
      - Testing the s3gw: "testing.md"
      - UI: "ui.md"
      - S3 API compatibility table: "s3-compatibility-table.md"
      - Metrics: "metrics.md"
  - "Team Decisions":
      - Use markdown any decision records: "decisions/0000-use-markdown-any-decision-records.md"
      - Reorganize documentation: "decisions/0001-reorganize-documentation.md"
      - s3gw storage backend: "decisions/0002-s3gw-storage-backend.md"
      - SFS SAL backend design: "decisions/0003-sfs.md"
      - Release captain: "decisions/0004-release-captain.md"
      - Project labels: "decisions/0005-project-labels.md"
      - Git branches tags: "decisions/0006-git-branches-tags.md"
      - Release process: "decisions/0007-release-process.md"
      - Pull requests and code review guide: "decisions/0008-pull-requests-code-review-guide.md"
  - "Design Documents":
      - UI backend: "design/0001-ui-backend.md"
  - "Release Notes":
      - v0.1.0: "release-notes/s3gw-v0.1.0.md"
      - v0.2.0: "release-notes/s3gw-v0.2.0.md"
      - v0.3.0: "release-notes/s3gw-v0.3.0.md"
      - v0.4.0: "release-notes/s3gw-v0.4.0.md"
      - v0.5.0: "release-notes/s3gw-v0.5.0.md"
      - v0.6.0: "release-notes/s3gw-v0.6.0.md"
      - v0.7.0: "release-notes/s3gw-v0.7.0.md"
      - v0.8.0: "release-notes/s3gw-v0.8.0.md"
      - v0.9.0: "release-notes/s3gw-v0.9.0.md"
      - v0.9.1: "release-notes/s3gw-v0.9.1.md"
      - v0.10.0: "release-notes/s3gw-v0.10.0.md"
      - v0.11.0: "release-notes/s3gw-v0.11.0.md"
      - v0.12.0: "release-notes/s3gw-v0.12.0.md"
      - v0.13.0: "release-notes/s3gw-v0.13.0.md"
      - v0.14.0: "release-notes/s3gw-v0.14.0.md"
      - v0.15.0: "release-notes/s3gw-v0.15.0.md"
      - v0.16.0: "release-notes/s3gw-v0.16.0.md"
      - v0.17.0: "release-notes/s3gw-v0.17.0.md"
  - "About and License":
      - Repositories: "s3gw-repos.md"
      - License: "license.md"
