apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: cors-header
  namespace: s3gw-system
spec:
  headers:
    accessControlAllowMethods:
      - "GET"
      - "HEAD"
      - "PUT"
      - "POST"
      - "DELETE"
      - "OPTIONS"
    accessControlAllowOriginList:
      - "*"
    accessControlAllowHeaders:
      - "*"
    accessControlExposeHeaders:
      - "ETag"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: s3gw-ingress
  namespace: s3gw-system
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: s3gw-system-cors-header@kubernetescrd
spec:
  tls:
    - hosts:
        - s3gw.local
      secretName: s3gw-ingress-secret
  rules:
    - host: s3gw.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: s3gw-service
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: s3gw-no-tls-ingress
  namespace: s3gw-system
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: s3gw-system-cors-header@kubernetescrd
spec:
  rules:
    - host: s3gw.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: s3gw-service
                port:
                  number: 80
