- name: s3gw-ui build image
  hosts: kubectl
  become: true
  tasks:

    - name: Copy s3gw-ui directory to local directory
      copy: src=../s3gw-ui dest=/home/{{ user }} mode=0777

    - name: Set S3GW_UI_IMAGE in s3gw-ui-deployment.yaml
      replace:
        path: /home/{{ user }}/s3gw-ui/s3gw-ui-deployment.yaml
        regexp: '##S3GW_UI_IMAGE##'
        replace: "{{ s3gw_ui_image }}"

    - name: Set S3GW_UI_IMAGE_PULL_POLICY in s3gw-ui-deployment.yaml
      replace:
        path: /home/{{ user }}/s3gw-ui/s3gw-ui-deployment.yaml
        regexp: '##S3GW_UI_IMAGE_PULL_POLICY##'
        replace: "{{ s3gw_ui_image_pull_policy }}"

    - name: Copy Dockerfile.s3gw-ui to local directory
      copy: src=../../build-ui/Dockerfile.s3gw-ui dest=/home/{{ user }}/s3gw-ui mode=0777

    - name: Git s3gw-ui checkout
      git:
        repo: "{{ s3gw_ui_repo }}"
        dest: /home/{{ user }}/s3gw-ui/s3gw-ui
        version: "{{ s3gw_ui_version }}"

    - name: Build s3gw-ui image
      community.docker.docker_image:
       build:
          path: /home/{{ user }}/s3gw-ui/s3gw-ui
          dockerfile: /home/{{ user }}/s3gw-ui/Dockerfile.s3gw-ui
       name: s3gw-ui
       tag: latest
       source: build

    - name: Tag and push s3gw-ui to local registry
      community.docker.docker_image:
        name: s3gw-ui
        repository: admin-1:5000/s3gw-ui
        tag: latest
        push: yes
        source: local

- name: s3gw UI deploy
  hosts: kubectl
  tasks:

    - name: Apply s3gw-ui-deployment.yaml
      kubernetes.core.k8s:
        state: present
        src: /home/{{ user }}/s3gw-ui/s3gw-ui-deployment.yaml

    - name: Apply s3gw-ui-service.yaml
      kubernetes.core.k8s:
        state: present
        src: /home/{{ user }}/s3gw-ui/s3gw-ui-service.yaml

