---
name: Release S3GW
on:
  schedule:
    - cron: '30 4 * * 1-6'  # Every night 4:30 except sunday

  push:
    tags:
      - "v*"

jobs:
  set-git-refs:
    runs-on: ubuntu-latest

    outputs:
      ceph-git-ref: ${{ steps.git-refs.outputs.ceph }}
      tools-git-ref: ${{ steps.git-refs.outputs.tools }}
      ui-git-ref: ${{ steps.git-refs.outputs.ui }}
      charts-git-ref: ${{ steps.git-refs.outputs.charts }}
      github-ref-name: ${{ steps.git-refs.outputs.github-ref-name }}

    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set Git Refs
        id: git-refs
        run: |
          for r in $(git submodule | awk '{print $2}'); do
            echo "::set-output name=${r}::$(git log -1 --format="%H" "${r}")"
          done
          echo "::set-output name=github-ref-name::${GITHUB_REF_NAME:-nightly}"


  # Build the build-environment container, using it's workflow
  build-env:
    runs-on: ubuntu-latest
    needs:
      - set-git-refs

    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Dockerhub Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Buildenv Container
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/buildenv-radosgw:${{ needs.set-git-refs.outputs.github-ref-name }}
          file: tools/build/Dockerfile.build-radosgw
          context: tools/build

  # Build the radosgw binary using the previously built container image
  build-radosgw:
    runs-on: ubuntu-latest
    needs:
      - set-git-refs
      - build-env

    outputs:
      artifact_id: ${{ steps.artifact_id.outputs.artifact_id }}

    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: aquarist-labs/ceph
          ref: ${{ needs.outputs.ceph-git-ref }}
          submodules: recursive
          path: ceph

      - name: Create CCache Timestamp
        id: ccache_timestamp
        run: |
          echo "::set-output name=timestamp::$(date +%Y-%m-%d-%H:%M:%S)"

      - name: Cache CCache Files
        uses: actions/cache@v3.0.4
        with:
          path: ceph/build.ccache
          key: ccache-${{ steps.ccache_timestamp.outputs.timestamp }}
          restore-keys: |
            ccache-

      - name: Build radosgw Binary
        run: |
          docker run --rm \
            -v $GITHUB_WORKSPACE/ceph:/srv/ceph \
            -e NPROC=4 \
            -e CMAKE_BUILD_TYPE=Release \
            ${{ secrets.DOCKERHUB_USERNAME }}/buildenv-radosgw:${{ needs.set-git-refs.outputs.github-ref-name }}

      - name: Compress Build Results
        run: |
          tar -czvf build-results.tar.gz \
            ceph/build/bin/radosgw \
            ceph/build/lib/libceph-common.so \
            ceph/build/lib/libceph-common.so.2 \
            ceph/build/lib/libradosgw.so \
            ceph/build/lib/libradosgw.so.2 \
            ceph/build/lib/libradosgw.so.2.0.0 \
            ceph/build/lib/librados.so \
            ceph/build/lib/librados.so.2 \
            ceph/build/lib/librados.so.2.0.0

      - name: Generate Artifact Identifier
        id: artifact_id
        run: |
          ARTIFACT_ID=radosgw-$GITHUB_REF_NAME
          echo "::set-output name=artifact_id::$ARTIFACT_ID"

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.artifact_id.outputs.artifact_id }}
          path: build-results.tar.gz

  # Build and push the radosgw container using the radosgw-binary
  build-s3gw-container:
    runs-on: ubuntu-latest
    needs:
      - set-git-refs
      - build-radosgw

    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Dockerhub Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Download Radogw Artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.build-radosgw.outputs.artifact_id }}

      - name: Unpack Artifacts
        run: |
          tar -xvf build-results.tar.gz

      - name: Build S3GW Container
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/${{ secrets.GHCR_USERNAME }}/s3gw:${{ needs.set-git-refs.outputs.github-ref-name }}
          file: tools/build/Dockerfile.build-container
          context: ceph/build

  # Build and push the ui container
  build-ui:
    runs-on: ubuntu-latest
    needs:
      - set-git-refs

    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Dockerhub Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and Push Container
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/${{ secrets.GHCR_USERNAME }}/s3gw-ui:${{ needs.set-git-refs.outputs.github-ref-name }}
          file: ui/Dockerfile
          context: ui

  # Release the charts
  # TODO
