---
name: Release S3GW
on:
  schedule:
    - cron: '30 4 * * 1-6'  # Every night 4:30 except sunday

  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set Git Refs
        id: git-refs
        run: |
          for r in $(git submodule | awk '{print $2}'); do
            echo "::set-output name=${r}::$(git log -1 --format="%H" "${r}")"
          done
          echo "::set-output name=github-ref-name::${GITHUB_REF_NAME:-nightly}"

      # Build the build-environment container, using it's workflow
      - name: Build Environment
        uses: ./s3gw-tools/.github/workflows/build-environment.yaml
        with:
          tag: ${{ steps.git-refs.outputs.github-ref-name }}
          ref: ${{ steps.git-refs.outputs.tools-git-ref }}

      # Build the radosgw binary using the previously built container image
      - name: Build Radosgw Binary
        uses: ./ceph/.github/workflows/build-radosgw.yaml
        with:
          tag: ${{ steps.git-refs.outputs.github-ref-name }}
          ref: ${{ steps.git-refs.outputs.ceph-git-ref }}

  # Build and push the radosgw container using the radosgw-binary
  # TODO

  # Build and push the ui container
  # TODO

  # Release the charts
  # TODO
